# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/George/Desktop/NES/nes/NES_CPU.srcs/sources_1/ip/Test_ROM_v2/Test_ROM_v2.xci
# IP: The module: 'Test_ROM_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/NES/nes/NES_CPU.gen/sources_1/ip/Test_ROM_v2/Test_ROM_v2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_ROM_v2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/George/Desktop/NES/nes/NES_CPU.srcs/sources_1/ip/Test_ROM_v2/Test_ROM_v2.xci
# IP: The module: 'Test_ROM_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/NES/nes/NES_CPU.gen/sources_1/ip/Test_ROM_v2/Test_ROM_v2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Test_ROM_v2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
