#create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]

set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN T13 [get_ports {gpio_usb_int_tri_i[0]}]
set_property PACKAGE_PIN V14 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN V15 [get_ports usb_spi_mosi]
set_property PACKAGE_PIN U12 [get_ports usb_spi_miso]

set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN V13 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN T12 [get_ports usb_spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]


set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[0]}]
set_property PACKAGE_PIN G6 [get_ports {hex_gridA[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_gridA[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_gridA[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_gridA[3]}]
set_property PACKAGE_PIN E6 [get_ports {hex_segA[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_segA[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_segA[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_segA[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_segA[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_segA[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_segA[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_segA[7]}]
set_property PACKAGE_PIN F3 [get_ports {hex_segB[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_segB[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_segB[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_segB[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_segB[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_segB[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_segB[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_segB[7]}]
set_property PACKAGE_PIN E4 [get_ports {hex_gridB[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_gridB[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_gridB[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_gridB[3]}]



#HDMI Signals
set_property -dict {PACKAGE_PIN V17 IOSTANDARD TMDS_33} [get_ports hdmi_tmds_clk_n]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD TMDS_33} [get_ports hdmi_tmds_clk_p]

set_property -dict {PACKAGE_PIN U18 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_n[2]}]

set_property -dict {PACKAGE_PIN U17 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p[0]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p[1]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD TMDS_33} [get_ports {hdmi_tmds_data_p[2]}]

#Switches
set_property IOSTANDARD LVCMOS25 [get_ports {SW[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[0]}]

set_property PACKAGE_PIN G1 [get_ports {SW[0]}]
set_property PACKAGE_PIN F2 [get_ports {SW[1]}]
set_property PACKAGE_PIN F1 [get_ports {SW[2]}]
set_property PACKAGE_PIN E2 [get_ports {SW[3]}]
set_property PACKAGE_PIN E1 [get_ports {SW[4]}]
set_property PACKAGE_PIN D2 [get_ports {SW[5]}]
set_property PACKAGE_PIN D1 [get_ports {SW[6]}]
set_property PACKAGE_PIN C2 [get_ports {SW[7]}]
set_property PACKAGE_PIN B2 [get_ports {SW[8]}]
set_property PACKAGE_PIN A4 [get_ports {SW[9]}]
set_property PACKAGE_PIN A5 [get_ports {SW[10]}]
set_property PACKAGE_PIN A6 [get_ports {SW[11]}]
set_property PACKAGE_PIN C7 [get_ports {SW[12]}]
set_property PACKAGE_PIN A7 [get_ports {SW[13]}]
set_property PACKAGE_PIN B7 [get_ports {SW[14]}]
set_property PACKAGE_PIN A8 [get_ports {SW[15]}]

#Button
set_property PACKAGE_PIN J1 [get_ports Run]
set_property IOSTANDARD LVCMOS25 [get_ports Run]





set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[3]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[7]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[11]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[14]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[2]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[6]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[0]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[5]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[9]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[10]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[13]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[1]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[4]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[8]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[12]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addra[15]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[5]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[9]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[10]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[13]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[2]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[8]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[11]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[12]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[15]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[1]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[3]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[4]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[7]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[14]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[0]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/addrb[6]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[0]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[1]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[2]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[3]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[4]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[5]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[6]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/dina[7]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[0]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[1]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[2]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[3]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[4]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[5]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[6]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/doutb[7]}]
set_property MARK_DEBUG false [get_nets {vga/blk_ram/wea[0]}]
set_property MARK_DEBUG false [get_nets clk_divider3/clk_out2]
set_property MARK_DEBUG false [get_nets vga/blk_ram/clkb]
set_property MARK_DEBUG false [get_nets vga/blk_ram/clka]
